Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Asic: # Note: Configuration tuned for ASIC Board V2: #6
      ##########################################################################
      Gpio:
        RSTB_RAM: 0x1
        RST_COUNTER: 0x0
        DlyCalPulseSet: 2450 # Rising edge of EXT_TRIG
        DlyCalPulseReset: 0 # Falling edge of EXT_TRIG, keeps ext trig OFF
      TdcClk:
        Tdc40MHzClkSel: Pll
        FpgaTdcClkHigh: 0x1
        FpgaTdcClkLow: 0x1
      ##########################################################################
      Trig:
        enable: True
        TrigTypeSel: Master
        CalStrobeAlign: 0x3
        TrigStrobeAlign: 0x3
        EnCalPulseTrig: 0x1
        EnBncExtTrig: 0x0
        EnPcieLocalTrig: 0x0
        EnLemoRemoteTrig: 0x0
        MasterModeSel: OR
        ReadoutStartDly: 0x128
        TrigSizeBeforePause: 0x0
        DeadtimeDuration: 0x0
        EnableReadout: 0x1

      SlowControl:
        ########################
        ########################
#######################         Nikola    ########################
        EN_ck_SRAM[:]: 0x1
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x0 #0 => ON
       

 ########################
        #Threshold alignment. DAC cor 7 bits 0x40= 64 decimal (mid range) #
        bit_vth_cor[:]: 64 # 
        DAC10bit: 404
        bit_vth_cor[0]: 58   #416 404
        bit_vth_cor[1]: 62   #408 404
        bit_vth_cor[2]: 61   #410 404
        bit_vth_cor[3]: 43   #446 404
        bit_vth_cor[4]: 113   #306 404
        bit_vth_cor[5]: 56   #420 404
        bit_vth_cor[6]: 68   #396 404
        bit_vth_cor[7]: 25   #482 404
        bit_vth_cor[8]: 56   #420 404
        bit_vth_cor[9]: 92   #348 404
        bit_vth_cor[10]: 56   #420 404
        bit_vth_cor[11]: 1   #999999999 404
        bit_vth_cor[12]: 38   #456 404
        bit_vth_cor[13]: 75   #382 404
        bit_vth_cor[14]: 92   #348 404

        ########################

        ON_discri[:]: 0x1
        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        cBit_f_TOA[:]: 0x0     # increase to 0 to f to reduce LSB while keeping cBit_s_TOA=0   
        cBit_s_TOA[:]: 0x0
        cBit_f_TOT[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_c_TOT[:]: 0xf
        
        DLL_ALockR_en: 0x0 # should be kept to 1
        CP_b: 0x5 #5 WO Ileak on Vctrl, Charge pump I only detremines the velocity of DLL locking and not the value to which it locks
        
        ext_Vcrtlf_en: 0x1
        ext_Vcrtls_en: 0x1
        ext_Vcrtlc_en: 0x1

        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toa_satovfw: 0x1      
      
        SatFVa: 0x4 #3
        IntFVa: 0x0 #1
        SatFTz: 0x4 #4
        IntFTz: 0x1 #1  
      
        cBitf: 0x0 #0 # decrease from f to 0 to reduce LSB while increasing cBits to f 
        cBits: 0x0 #f
        cBitc: 0x0 #f      
      
        Rin_Vpa: 0x0 #0 0 => 25K, 1 => 15K. Set to 1 to avoid couplings with TOA busyb (sensor)
        Cp_Vpa: 0x0
      
        cd[0]: 0x0 #6
        cd[1]: 0x0 #6
        cd[2]: 0x0 #6
   
        dac_biaspa: 0x1e #10
        ON_dac_biaspa: 0x1
        dac_pulser: 12 #7
      
        #DAC10bit: 310 #173 / 183

        ON_dac_LR: 0x0
        Ck40_choice: 0x1
        en_8drivers: 0x1

        PLL: 0x0
        Shifted_ck40: 0x0
        #dac_CP_BWb: 0x10 # V2 maps dac_CP_BW<0> to Shifted_ck40

      
      ##########################################################################
      Readout:
        #####################
        RstRamPulseWidth: 0xF
        ProbeToRstDly: 0x0  # Min. tuned on 18JULY2019:LLR
        RstPulseWidth: 0xF
        RstToReadDly: 0x0   # Min. tuned on 18JULY2019:LLR
        RckHighWidth: 0x2   # Min. tuned on 18JULY2019:LLR
        RckLowWidth: 0x2    # Min. tuned on 18JULY2019:LLR
        #####################
        RestoreProbeConfig: 0x1 #1 sets probe in previous config
        EnProbeWrite: 0x1
        OnlySendFirstHit: 0x1
        #Probe cofiguration
        EnProbeDigOutDisc: 0x0
        EnProbeDigSelect: 0x0
        EnProbeDig: 0x0
        EnProbePa: 0x0
        #####################
        RdIndexLut[0]: 0
        RdIndexLut[1]: 1
        RdIndexLut[2]: 2
        RdIndexLut[3]: 3
        RdIndexLut[4]: 4
        RdIndexLut[5]: 5
        RdIndexLut[6]: 6
        RdIndexLut[7]: 7
        RdIndexLut[8]: 8
        RdIndexLut[9]: 9
        RdIndexLut[10]: 10
        RdIndexLut[11]: 11
        RdIndexLut[12]: 12
        RdIndexLut[13]: 13
        RdIndexLut[14]: 14
        RdIndexLut[15]: 15
        RdIndexLut[16]: 16
        RdIndexLut[17]: 17
        RdIndexLut[18]: 18
        RdIndexLut[19]: 19
        RdIndexLut[20]: 20
        RdIndexLut[21]: 21
        RdIndexLut[22]: 22
        RdIndexLut[23]: 23
        RdIndexLut[24]: 24
        ReadoutSize: 0
  LiveDisplayRst: 0
