Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Asic: # Note: Configuration tuned for ASIC Board V2: #6
      ##########################################################################
      Trig:
        CalStrobeAlign: 0x3 # Cal pulse 40 Mhz alignment to 160 MHz
        EnCalPulseTrig: 0x1 # Enable Cal pulse to trigger readout      
      ##########################################################################
      SlowControl:
        ########################
        EN_ck_SRAM[:]: 0x1
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x1
        bit_vth_cor[:]: 0x40
        ON_discri[:]: 0x0
        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        cBit_f_TOA[:]: 0x0        
        cBit_s_TOA[:]: 0x0
        cBit_f_TOT[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_c_TOT[:]: 0x0
        
        DLL_ALockR_en: 0x1
        CP_b: 0x5 #5
        
        ext_Vcrtlf_en: 0x1 #need to fix value externally
        ext_Vcrtls_en: 0x1 #need to fix value externally
        ext_Vcrtlc_en: 0x1 #0

        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toa_satovfw: 0x1      
      
        SatFVa: 0x4 #3
        IntFVa: 0x0 #1
        SatFTz: 0x4 #4
        IntFTz: 0x1 #1  
      
        cBitf: 0x0 #0
        cBits: 0x0 #f
        cBitc: 0x0 #f      
      
        Rin_Vpa: 0x0 #0
        Cp_Vpa: 0x0
      
        cd[0]: 0x7 #6
        cd[1]: 0x7 #6
        cd[2]: 0x7 #6
   
        dac_biaspa: 0x1e #10
        ON_dac_biaspa: 0x1
        dac_pulser: 12 #7
      
        DAC10bit: 350 #173 / 183

        ON_dac_LR: 0x0
        Ck40_choice: 0x1
        en_8drivers: 0x1

        PLL: 0x0
        Shifted_ck40: 0x0
        dac_CP_BWb: 0x10 # V2 maps dac_CP_BW<0> to Shifted_ck40
      ##########################################################################
      Probe:
        en_probe_pa: 0x0
        en_probe_dig: 0x1
        EN_dout: 0x1
        rstL: 0x1

      ##########################################################################
      Readout:
        RckHighWidth: 0x3
        RckLowWidth: 0x3
        RstToReadDly: 0xF
        OnlySendFirstHit: 0x1 # Only send the first hit per pixel
      ##########################################################################
