Top:
  Fpga[0]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Asic: # Note: Configuration tuned for ASIC Board V2: #6
      ##########################################################################
      Gpio:
        RSTB_RAM: 0x1
        RST_COUNTER: 0x0
        DlyCalPulseSet: 2450 # Rising edge of EXT_TRIG
        DlyCalPulseReset: 0 # Falling edge of EXT_TRIG
      Trig:
        TrigTypeSel: Master
        CalStrobeAlign: 0x3      # Same as calibration pulse testing
        TrigStrobeAlign: 0x3     # Sets 6.25 ns trigger window w.r.t to 40 MHz clock  (might need tuning for the real system)
        EnCalPulseTrig: 0x0      # Disable calibration pulse
        EnBncExtTrig: 0x0        # Disable BNC external trigger
        EnPcieLocalTrig: 0x1     # Enable the local TOA_BUSY trigger
        EnLemoRemoteTrig: 0x1    # Enable the remote TOA_BUSY trigger   
        MasterModeSel: OR        # Either OR or AND the TOA_BUSY triggers together (inverted to active HIGH logic in FW)
        ReadoutStartDly: 128     # Units of 6.4ns (might need tuning for the real system)
        TrigSizeBeforePause: 0x0 # number of triggers before o-scope deadtime (zero bypass deadtime
        DeadtimeDuration: 0x0    # number of seconds to hold off readout until o-scope recovers
        EnableReadout: 0x0       # prevents either o-scope or dataStream from receiving data until enabled
      TdcClk:
        Tdc40MHzClkSel: Pll
        FpgaTdcClkHigh: 0x1
        FpgaTdcClkLow: 0x1
      CalPulse:
        CalPulseWidth: 0x2 
        Continuous: 0x0 
      ##########################################################################
      SlowControl:
        ########################
        #general settings -> all on
        EN_ck_SRAM[:]: 0x1
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x0
        ON_discri[:]: 0x1
        bit_vth_cor[:]: 0x40
       
        ###################
        #turn off broken channels
        EN_ck_SRAM[0]: 0x0 
        EN_ck_SRAM[9]: 0x0 
        EN_ck_SRAM[11]: 0x0 

        disable_pa[0]: 0x1 
        disable_pa[9]: 0x1 
        disable_pa[11]: 0x1 

        ON_discri[0]: 0x0 
        ON_discri[9]: 0x0 
        ON_discri[11]: 0x0 
        ###################
        ##set correct vth correction
        bit_vth_cor[1]: 45
        bit_vth_cor[2]: 45
        bit_vth_cor[3]: 45
        bit_vth_cor[4]: 45
        bit_vth_cor[5]: 45
        bit_vth_cor[6]: 45
        bit_vth_cor[7]: 75
        bit_vth_cor[8]: 90
        bit_vth_cor[10]: 35
        bit_vth_cor[11]: 35
        bit_vth_cor[12]: 85
        bit_vth_cor[13]: 75
        bit_vth_cor[14]: 65

        ###################

        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        cBit_f_TOA[:]: 0x0        
        cBit_s_TOA[:]: 0x0
        cBit_f_TOT[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_c_TOT[:]: 0x0
        
        DLL_ALockR_en: 0x1
        CP_b: 0x4 #5
        
        ext_Vcrtlf_en: 0x1 #need to fix value externally
        ext_Vcrtls_en: 0x1 #need to fix value externally
        ext_Vcrtlc_en: 0x1 #0

        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toa_satovfw: 0x1      
      
        SatFVa: 0x4 #3
        IntFVa: 0x0 #1
        SatFTz: 0x4 #4
        IntFTz: 0x1 #1  
      
        cBitf: 0x0 #0
        cBits: 0x0 #f
        cBitc: 0x0 #f      
      
        Rin_Vpa: 0x0 #0
        Cp_Vpa: 0x0
      
        cd[0]: 0x0 #6
        cd[1]: 0x0 #6
        cd[2]: 0x0 #6
   
        dac_biaspa: 0x1e #10
        ON_dac_biaspa: 0x1
        dac_pulser: 12 #7
      
        DAC10bit: 485 #average

        ON_dac_LR: 0x0
        Ck40_choice: 0x1
        en_8drivers: 0x1

        PLL: 0x0
        Shifted_ck40: 0x0
        #dac_CP_BWb: 0x10 # V2 maps dac_CP_BW<0> to Shifted_ck40


      ##########################################################################
      Readout:
        ReadoutSize: 12
        RdIndexLut[0]: 1
        RdIndexLut[1]: 2
        RdIndexLut[2]: 3
        RdIndexLut[3]: 4
        RdIndexLut[4]: 5
        RdIndexLut[5]: 6
        RdIndexLut[6]: 7
        RdIndexLut[7]: 8
        RdIndexLut[8]: 10
        RdIndexLut[9]: 12
        RdIndexLut[10]: 13
        RdIndexLut[11]: 14


        #####################
        RstRamPulseWidth: 0xF
        ProbeToRstDly: 0x0  # Min. tuned on 18JULY2019:LLR
        RstPulseWidth: 0xF
        RstToReadDly: 0x0   # Min. tuned on 18JULY2019:LLR
        RckHighWidth: 0x2   # Min. tuned on 18JULY2019:LLR
        RckLowWidth: 0x2    # Min. tuned on 18JULY2019:LLR
        #####################
        RestoreProbeConfig: 0x0
        EnProbeWrite: 0x1
        OnlySendFirstHit: 0x1
        #####################

