Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Asic: # Note: Configuration tuned for ASIC Board V2: #6
      ##########################################################################
      Trig:
        CalStrobeAlign: 0x3 # Cal pulse 40 Mhz alignment to 160 MHz
        EnCalPulseTrig: 0x1 # Enable Cal pulse to trigger readout      
        EnableReadout: 0x1
      ##########################################################################
      SlowControl:
        ########################
        EN_ck_SRAM[:]: 0x1
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x1
        bit_vth_cor[:]: 0x40
        ON_discri[:]: 0x0
        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        cBit_f_TOA[:]: 0x0        
        cBit_s_TOA[:]: 0x0
        cBit_f_TOT[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_c_TOT[:]: 0x0
        ########################
        EN_ck_SRAM[4]: 0x1
        ON_Ctest[4]: 0x1
        disable_pa[4]: 0x0
        bit_vth_cor[4]: 0x40
        ON_discri[4]: 0x0
        EN_hyst[4]: 0x1
        EN_trig_ext[4]: 0x1
        cBit_f_TOA[4]: 0x0 #0
        cBit_s_TOA[4]: 0x0 #0
        cBit_f_TOT[4]: 0x0 #f
        cBit_s_TOT[4]: 0x0 #0
        cBit_c_TOT[4]: 0x0 #f
        ########################     
        
        DLL_ALockR_en: 0x1
        CP_b: 0x7 #5
        
        ext_Vcrtlf_en: 0x1 #0
        ext_Vcrtls_en: 0x1 #need to fix value externally
        ext_Vcrtlc_en: 0x0 #0

        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toa_satovfw: 0x1      
      
        SatFVa: 0x3 #3
        IntFVa: 0x0 #1
        SatFTz: 0x4 #4
        IntFTz: 0x1 #1  
      
        cBitf: 0x0 #0
        cBits: 0x0 #6
        cBitc: 0x0 #0      
      
        Rin_Vpa: 0x0 #0
      
        cd[0]: 0x7 #6
        cd[1]: 0x7 #6
        cd[2]: 0x7 #6
   
        dac_biaspa: 0x1e #10
        dac_pulser: 12 #7
      
        DAC10bit: 371 #173 / 183

        ON_dac_LR: 0x0
        Ck40_choice: 0x1
        en_8drivers: 0x1

        PLL: 0x0
        Shifted_ck40: 0x0
      ##########################################################################
      Probe:
        EN_dout: 0x1
        en_probe_pa: 0x0
        en_probe_dig: 0x0 # pix
        pix[4]:
          probe_pa: 0x0
          probe_vthc: 0x0
          probe_dig_out_disc: 0x0
          probe_toa: 0x0
          probe_tot: 0x0
          totf: 0x0
          tot_overflow: 0x0
          toa_busy: 0x0
          tot_busy: 0x0
          tot_ready: 0x0
          en_read: 0x1
          toa_busy: 0x0
      ##########################################################################
      Readout:
        RckHighWidth: 0x3
        RckLowWidth: 0x3
        RstToReadDly: 0xF
        ReadoutSize: 0 # 0 pixel readout (zero inclusive)
        RdIndexLut[0]: 4 # pix=4
        OnlySendFirstHit: 0x1 # Only send the first hit per pixel
      ##########################################################################
